# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1111}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Server
server.port=${SERVER_PORT:8080}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}

spring.jpa.open-in-view=false

# File Upload
file.upload-dir=${FILE_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
