package com.sharebite.backend.entity;

public enum NotificationType {
    REQUEST_CREATED,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    REQUEST_CANCELED,
    REQUEST_COMPLETED,
    NEW_MESSAGE,
    LISTING_EXPIRED,
    LISTING_REMOVED,
    MODERATION_WARNING,
    ACCOUNT_SUSPENDED,
    ACCOUNT_MONITORED,
    REPORT_ESCALATED
}
